
version: 2

models:
    - name: applicant
      description: "A starter dbt model"
      columns:
          - name: APPLICANT
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: permits
      description: "A starter dbt model"
      columns:
          - name: PERMIT_NUMBER
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
